### ISSUE TITLE
EmbeddedGroups results

### ISSUE THREAD

**Issue by Patrock** [TremoloSecurity/MyVirtualDirectory#21]
I just made tests with EmbeddedGroups insert (on global chain or on directory chain)

When i make a search a member in groupOfNames without objectclass (just member=cn=XYZ,dc=abc), i get other users and ou's  in result list.

Without EmbeddedGroup insert, i get only groupOfNames (naturally not recusrive ;)

Is it a bug ?

**Comment by mlbiam** [comment]
Could be.  I would add the net.sourceforge.myvd.inserts.mapping.AttributeCleaner insert to the global chain with clearAttributes set to true.  This will tell MyVD to request all attributes BUT only return attributes you asked for to the client.  Inserts don't always do a great job of asking for attributes that are needed based on the filter.  This way MyVD gets everything it might need then strips out what isn't needed before its sent back to the client.

**Comment by Patrock** [comment]
@mlbiam i'll tried without success,..

I don't mean i get too much attributes on objects. i'm getting too much objects...

not only get the right groupOfNames-Objects but additionally getting OrganizationalUnit-objects,, inetOrgPerson-Objects etc...


Thank you...

**Comment by mlbiam** [comment]
@Patrock right, understood.  Thats happening because MyVD is making incorrect decisions because its not asking for the correct attributes from the downstream server.  By asking for more attributes, MyVD will know to trim the objects that its retrieving.

**Comment by Patrock** [comment]
@mlbiam okay, understood, in my service apps it no problem because the objectClass is asked together with member, but in my tests sometimes i just strip something and then i got suspicous ;)

Thank you again...

**Comment by mlbiam** [comment]
@Patrock wanted to circle back, is everything working for you?

**Comment by Patrock** [comment]
@mlbiam currently the most things are working. The only thing is still the issue, that i can't see/query the RottDSE when using vmemberof and embeddedgroups in the global chain (see [https://github.com/TremoloSecurity/MyVirtualDirectory/issues/15#issuecomment-271496617](url)

As i said i'M using ApacheDS to manage my directory. Because i can't load a schema i have to manage the directories seperatly (its difficult to insert an object withoot schema in ApacheDS). I tried SchemaInsert just like in the example with the openldap_schema.ldif, but i still can't see a schema).

But it's nothing critical, if there is time we can get into this ;)

**Comment by Patrock** [comment]
@mlbian could it be, that embeddedgroups aren't recursive through multiple levels ?

i have the following structure:

group: app_users
member: workgroup1_users

group: workgroup1_users
member: workgroup1_employees
member: workgroup1_guests
member: workgroup1_students

group: workgroup1_employees
member: userXYZ

in group app_users i only get a member workgroup1_employees but no userXYZ

Would it be difficult to obtain ?

Tanks

Patrick

**Comment by mlbiam** [comment]
@Patrock hmm, it should.  i need to setup a test environment to see if i can reproduce.  Also, you might want to make sure you are using the latest from 1.0.1, I fixed some routing issues

**Comment by Patrock** [comment]
@mlbiam ok, thank you. I have pulled after the 58. commit, so it should be up to date, but i will check it later...

**Comment by Patrock** [comment]
@mlbiam found the error:

EmbeddedGroups.java:402
change
```
if (groups.contains(memberDN)) { ... }
```
to
``` 
if (groups.contains(memberDN.toString().toLowerCase())) { ... }
```

**Comment by mlbiam** [comment]
@Patrock awesome!  want to submit a PR?

**Comment by Patrock** [comment]
@mlbiam didn't made a pull request until now... ;) have i to fork your repo and push my changes ?

**Comment by mlbiam** [comment]
@Patrock exactly, fork it into your own repository and once you make the change create a PR (reference this issue)

**Comment by Patrock** [comment]
okay, pull Request done

**Comment by mlbiam** [comment]
merged, running integration tests now
