### ISSUE TITLE
Handling writes on a Joined directory

### ISSUE THREAD

**Issue by sickfear** [TremoloSecurity/MyVirtualDirectory#29]
Hi,

We've got two LDAP directories. Our enterprise one to be used to handle authentication (read only) and our own OpenLDAP for authorization (full access).

ProxyDN on OpenLDAP has full rights while ProxyDN on our EnterpriseLDAP has read only access.

Here is the join configuration
`server.LDAP1.chain=LDAPServer`
`server.LDAP1.nameSpace=o=enterprise,dc=XXX,dc=XXX`
`server.LDAP1.weight=1`
`server.LDAP1.LDAPServer.className=net.sourceforge.myvd.inserts.ldap.LDAPInterceptor`
`server.LDAP1.LDAPServer.config.host=server1address`
`server.LDAP1.LDAPServer.config.port=389`
`server.LDAP1.LDAPServer.config.remoteBase=dc=XXX,dc=XXX,dc=XXX`
`server.LDAP1.LDAPServer.config.proxyDN=cn=StandardApplicativeUser,ou=XXX,dc=XXX,dc=XXX,dc=XXX`
`server.LDAP1.LDAPServer.config.proxyPass=XXXXX`

`server.LDAP2.chain=LDAPServer`
`server.LDAP2.nameSpace=o=openldap,dc=XXX,dc=XXX`
`server.LDAP2.weight=1`
`server.LDAP2.LDAPServer.className=net.sourceforge.myvd.inserts.ldap.LDAPInterceptor`
`server.LDAP2.LDAPServer.config.host=server2address`
`server.LDAP2.LDAPServer.config.port=389`
`server.LDAP2.LDAPServer.config.remoteBase=dc=XXX,dc=XXX,dc=XXX`
`server.LDAP2.LDAPServer.config.proxyDN=cn=Super User,ou=XXX,dc=XXX,dc=XXX,dc=XXX`
`server.LDAP2.LDAPServer.config.proxyPass=XXXXX`

`server.GlobalJoiner.chain=joiner`
`server.GlobalJoiner.nameSpace=o=joinedldap,dc=XXX,dc=XXX`
`server.GlobalJoiner.weight=1`
`server.GlobalJoiner.joiner.className=net.sourceforge.myvd.inserts.join.Joiner`
`server.GlobalJoiner.joiner.config.primaryNamespace=o=openldap,dc=XXX,dc=XXX`
`server.GlobalJoiner.joiner.config.joinedNamespace=o=enterprise,dc=XXX,dc=XXX`
`server.GlobalJoiner.joiner.config.joinedAttributes=sn,sAMAccountName,gecos,homeDirectory,manager,uid,displayname`
`server.GlobalJoiner.joiner.config.joinFilter=(mail=ATTR.mail)`

- How can I handle writes and adds through MyVD? The idea is to redirect all the writes to LDAP2 server on which we have full rights
I tried to apply the configuration described on the documentation but it is not working as expected 
Indeed, whenever I try to access MyVD with authentication, I cannot even search for entries, only anonymous allows searches.

`server.Joiner.joinmod.className=net.sourceforge.myvd.inserts.join.SimpleJoinModify`
`server.Joiner.joinmod.config.joinerName=joiner`

**Comment by mlbiam** [comment]
Can you post the full config (minus secure info)?

**Comment by sickfear** [comment]
Sure, sorry, here you've got it

`#Listen on port 389`
`server.listener.port=390`

`#Listen on 636 using SSL`
`#server.secure.listener.port=636`
`#server.secure.keystore=/var/keystores/myvd.ks`
`#server.secure.keypass=secret`

`#Configure global chains`
`server.globalChain=LogAllTransactions`
`server.globalChain.LogAllTransactions.className=net.sourceforge.myvd.inserts.DumpTransaction`
`server.globalChain.LogAllTransactions.config.logLevel=debug`
`server.globalChain.LogAllTransactions.config.label=Global`

`#Configure namespaces`
`server.nameSpaces=Root,MNC,OPENLDAP,GlobalJoiner`

`server.Root.chain=RootDSE`
`server.Root.nameSpace=`
`server.Root.weight=0`
`server.Root.RootDSE.className=net.sourceforge.myvd.inserts.RootDSE`
`server.Root.RootDSE.config.namingContexts=o=joinedldap,dc=XXX,dc=XXX`
`#define the base server to provide an entry to connect internal and external users`


`server.UNIX.chain=mapLinuxAccount,LDAPServer`
`server.UNIX.nameSpace=o=unix,dc=XXX,dc=XXX`
`server.UNIX.weight=1`
`server.UNIX.LDAPServer.className=net.sourceforge.myvd.inserts.ldap.LDAPInterceptor`
`server.UNIX.LDAPServer.config.host=127.0.0.1`
`server.UNIX.LDAPServer.config.port=6389`
`server.UNIX.LDAPServer.config.remoteBase=ou=XXX,dc=XXX`
`server.UNIX.LDAPServer.config.proxyDN=uid=XXXreadOnly,ou=XXX,cn=XXX,ou=XXX,dc=XXX`
`server.UNIX.LDAPServer.config.proxyPass=XXX`
`server.UNIX.mapLinuxAccount.className=net.sourceforge.myvd.inserts.mapping.AttributeMapper`
`server.UNIX.mapLinuxAccount.config.mapping=linuxaccount=uid`

`server.OPENLDAP.chain=LDAPServer`
`server.OPENLDAP.nameSpace=o=openldap,dc=XXX,dc=XXX`
`server.OPENLDAP.weight=1`
`server.OPENLDAP.LDAPServer.className=net.sourceforge.myvd.inserts.ldap.LDAPInterceptor`
`server.OPENLDAP.LDAPServer.config.host=127.0.0.1`
`server.OPENLDAP.LDAPServer.config.port=1389`
`server.OPENLDAP.LDAPServer.config.remoteBase=dc=XXX,dc=XXX,dc=XXX`
`server.OPENLDAP.LDAPServer.config.proxyDN=cn=XXXFullAccess,ou=XXX,dc=XXX,dc=XXX,dc=XXX`
`server.OPENLDAP.LDAPServer.config.proxyPass=XXX`


`server.GlobalJoiner.chain=joiner`
`server.GlobalJoiner.nameSpace=o=joinedldap,dc=XXX,dc=XXX`
`server.GlobalJoiner.weight=1`
`server.GlobalJoiner.joiner.className=net.sourceforge.myvd.inserts.join.Joiner`
`server.GlobalJoiner.joiner.config.primaryNamespace=o=openldap,dc=XXX,dc=XXX`
`server.GlobalJoiner.joiner.config.joinedNamespace=o=unix,dc=XXX,dc=XXX`
`server.GlobalJoiner.joiner.config.joinedAttributes=sn,sAMAccountName,gecos,homeDirectory,manager,uid,displayname,unixaccount,linuxaccount`
`server.GlobalJoiner.joiner.config.joinFilter=(mail=ATTR.mail)`

**Comment by mlbiam** [comment]
First thing is lets make sure the individual directories are working.  With a joiner its best to have the joined directories to be in a different namespace:

`
#Listen on port 389
server.listener.port=390

#Listen on 636 using SSL
#server.secure.listener.port=636
#server.secure.keystore=/var/keystores/myvd.ks
#server.secure.keypass=secret

#Configure global chains
server.globalChain=LogAllTransactions
server.globalChain.LogAllTransactions.className=net.sourceforge.myvd.inserts.DumpTransaction
server.globalChain.LogAllTransactions.config.logLevel=debug
server.globalChain.LogAllTransactions.config.label=Global

#Configure namespaces
server.nameSpaces=Root,MNC,OPENLDAP,GlobalJoiner

server.Root.chain=RootDSE
server.Root.nameSpace=
server.Root.weight=0
server.Root.RootDSE.className=net.sourceforge.myvd.inserts.RootDSE
server.Root.RootDSE.config.namingContexts=o=joinedldap,dc=XXX,dc=XXX
#define the base server to provide an entry to connect internal and external users


server.UNIX.chain=mapLinuxAccount,LDAPServer
server.UNIX.nameSpace=o=unix,o=join
server.UNIX.weight=1
server.UNIX.LDAPServer.className=net.sourceforge.myvd.inserts.ldap.LDAPInterceptor
server.UNIX.LDAPServer.config.host=127.0.0.1
server.UNIX.LDAPServer.config.port=6389
server.UNIX.LDAPServer.config.remoteBase=ou=XXX,dc=XXX
server.UNIX.LDAPServer.config.proxyDN=uid=XXXreadOnly,ou=XXX,cn=XXX,ou=XXX,dc=XXX
server.UNIX.LDAPServer.config.proxyPass=XXX
server.UNIX.mapLinuxAccount.className=net.sourceforge.myvd.inserts.mapping.AttributeMapper
server.UNIX.mapLinuxAccount.config.mapping=linuxaccount=uid

server.OPENLDAP.chain=LDAPServer
server.OPENLDAP.nameSpace=o=openldap,o=join
server.OPENLDAP.weight=1
server.OPENLDAP.LDAPServer.className=net.sourceforge.myvd.inserts.ldap.LDAPInterceptor
server.OPENLDAP.LDAPServer.config.host=127.0.0.1
server.OPENLDAP.LDAPServer.config.port=1389
server.OPENLDAP.LDAPServer.config.remoteBase=dc=XXX,dc=XXX,dc=XXX
server.OPENLDAP.LDAPServer.config.proxyDN=cn=XXXFullAccess,ou=XXX,dc=XXX,dc=XXX,dc=XXX
server.OPENLDAP.LDAPServer.config.proxyPass=XXX


server.GlobalJoiner.chain=joiner
server.GlobalJoiner.nameSpace=o=joinedldap,dc=XXX,dc=XXX
server.GlobalJoiner.weight=1
server.GlobalJoiner.joiner.className=net.sourceforge.myvd.inserts.join.Joiner
server.GlobalJoiner.joiner.config.primaryNamespace=o=openldap,o=join
server.GlobalJoiner.joiner.config.joinedNamespace=o=unix,o=join
server.GlobalJoiner.joiner.config.joinedAttributes=sn,sAMAccountName,gecos,homeDirectory,manager,uid,displayname,unixaccount,linuxaccount
server.GlobalJoiner.joiner.config.joinFilter=(mail=ATTR.mail)
`

once its up and running, make sure you can search both your AD and your openldap individually.

**Comment by sickfear** [comment]
Hi,

Now it works, I had some wrong definition on the conf file

Thanks

Btw, congrats for this product, it will help us a lot to simplify our access management system!

**Comment by mlbiam** [comment]
Thanks!  if you have updated namespaces send them to me and i'll help build the ACLs you were looking for in #28
