### ISSUE TITLE
Sasl (GSSAPI) athentication

### ISSUE THREAD

**Issue by Delong-Yang** [TremoloSecurity/MyVirtualDirectory#38]
Hi @mlbiam ,
I found that novell LDAPConnection does not support Sasl authentication. We have an AD ldap server for some reason we cannot use simple authentication, but we have Kerberos ticket. I have problem to bind the connection. Can you please tell me how can I do that?

Thanks!

**Comment by mlbiam** [comment]
@Delong-Yang hmm, if you want you can try using the kerberose authenticator https://www.tremolosecurity.com/docs/tremolosecurity-docs/myvd/1.0.1/myvd.html to authenticate users but you'll still need an AD service account to manage data searches.

**Comment by mlbiam** [comment]
Why can't you do LDAP bind?
