### ISSUE TITLE
AD delegated authentication Configuration

### ISSUE THREAD

**Issue by partdeadpool-partpunisher** [TremoloSecurity/MyVirtualDirectory#52]
I have the following config: 
server.listener.port=10389

server.globalChain=

server.nameSpaces=ad2

server.ad2.chain=ldap2
server.ad2.nameSpace=o=dir2
server.ad2.weight=100
server.ad2.enabled=true
server.ad2.ldap2.className=net.sourceforge.myvd.inserts.ldap.LDAPInterceptor
server.ad2.ldap2.config.host=ad2dc1.testad.intranet-qx
server.ad2.ldap2.config.port=389
server.ad2.ldap2.config.remoteBase=dc=testad,dc=intranet-qx
server.ad2.ldap2.config.proxyDN=<<DN OF SERVICE ACCOUNT>>
server.ad2.ldap2.config.proxyPass=<<BIND PASSWORD>>

I have the proper DN and password in place in my test config.
I can authenticate as any account with an empty password (even made up ones), but nothing valid.
I've testing connecting with both ldp.exe and LDAP Admin (ldapadmin.org).
- ldp throws a java error on connect.
- ldap admin will connect but finds not objects.

Googling, I see others working with simple configs, but I am stumped.
- Windows Server 2012R2.
- java version "1.8.0_201"; 
 - - Java(TM) SE Runtime Environment (build 1.8.0_201-b09); 
 - - Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
- MyVirtualDirectory 1.0.4 from: https://www.tremolosecurity.com/downloads/
- Starting with: cscript myvd.vbs: Edited javaHome and myVDHome variables.

Thoughts?

**Comment by partdeadpool-partpunisher** [comment]
I have also tried with/without:
server.ad2.ldap2.config.ignoreRefs=true
server.ad2.ldap2.config.passBindOnly=true
server.ad2.ldap2.config.maxIdle=300000
server.ad2.ldap2.config.maxMillis=30000
server.ad2.ldap2.config.maxStaleTimeMillis=10000
server.ad2.ldap2.config.minimumConnections=10

**Comment by partdeadpool-partpunisher** [comment]
Update: My issue was around attempting to authenticate as uid=admin,ou=system.
When I switched to anonymous bind in LDAP Admin, it worked.
Then I added a RootDSE, and I have two directories under the root.
So, my questions now are:
 - How do I turn off anonymous bind?
 - How do I change the password for uid=admin,ou=system?

**Comment by partdeadpool-partpunisher** [comment]
Still testing, I see the following error:
```
Message ID : 230
    SearchRequest
        baseDn : 'o=mycompany,c=us'
        filter : '(objectclass=*)'
        scope : single level
        typesOnly : false
        Size Limit : no limit
        Time Limit : 60
        Deref Aliases : never Deref Aliases
        attributes : 'objectclass'
org.apache.directory.api.ldap.model.message.SearchRequestImpl@bf472462    Paged Search Control
        oid : 1.2.840.113556.1.4.319
        critical : true
        size   : '100'
        cookie   : ''
: Insufficient Access Rights:
org.apache.directory.api.ldap.model.exception.LdapNoPermissionException: Insufficient Access Rights
	at net.sourceforge.myvd.inserts.accessControl.AccessMgmt.checkPermisions(AccessMgmt.java:89)
....
```
So despite the ACI working with a scope of public, I tried to be explicit to the error with the following ACL chain:
```
server.globalChain=ACL

server.globalChain.ACL.className=net.sourceforge.myvd.inserts.accessControl.AccessMgmt
server.globalChain.ACL.config.numACIs=4
server.globalChain.ACL.config.aci.0=o=mycompany,c=us#subtree#grant:v,r,s,c,p#[entry]#subtree:ou=dir2,o=mycompany,c=us
server.globalChain.ACL.config.aci.1=o=mycompany,c=us#subtree#grant:v,r,s,c,p#[all]#subtree:ou=dir2,o=mycompany,c=us
server.globalChain.ACL.config.aci.2=CN=ROOTDSE#entry#grant:v,r,s,c,p#[entry]#subtree:ou=dir2,o=mycompany,c=us
server.globalChain.ACL.config.aci.3=CN=ROOTDSE#entry#grant:r,s,c,p#[all]#subtree:ou=dir2,o=mycompany,c=us

```
Still not working our for me and still not sure why, especially given the success simply changing the users from a valid subtree to public.

**Comment by partdeadpool-partpunisher** [comment]
Ok, I think I found a bug. Bob can bind, view, query with:
```
server.globalChain=ACL

server.globalChain.ACL.className=net.sourceforge.myvd.inserts.accessControl.AccessMgmt
server.globalChain.ACL.config.numACIs=6
server.globalChain.ACL.config.aci.0=o=mycompany,c=us#entry#grant:v#[entry]#dn:CN=Bob Smith,OU=Standard Users,ou=dir2,o=company,c=us
server.globalChain.ACL.config.aci.1=o=mycompany,c=us#subtree#grant:v#[entry]#dn:CN=Bob Smith,OU=Standard Users,ou=dir2,o=company,c=us
server.globalChain.ACL.config.aci.2=o=mycompany,c=us#entry#grant:r,s,c,p#[all]#dn:CN=Bob Smith,OU=Standard Users,ou=dir2,o=company,c=us
server.globalChain.ACL.config.aci.3=o=mycompany,c=us#subtree#grant:r,s,c,p#[all]#dn:CN=Bob Smith,OU=Standard Users,ou=dir2,o=company,c=us
server.globalChain.ACL.config.aci.4=CN=ROOTDSE#entry#grant:v#[entry]#public:
server.globalChain.ACL.config.aci.5=CN=ROOTDSE#entry#grant:r,s,c,p#[all]#public:
```

But gets an Insufficient rights error with:
```
server.globalChain=ACL

server.globalChain.ACL.className=net.sourceforge.myvd.inserts.accessControl.AccessMgmt
server.globalChain.ACL.config.numACIs=6
server.globalChain.ACL.config.aci.0=o=mycompany,c=us#entry#grant:v#[entry]#subtree:ou=dir2,o=company,c=us
server.globalChain.ACL.config.aci.1=o=mycompany,c=us#subtree#grant:v#[entry]#subtree:ou=dir2,o=company,c=us
server.globalChain.ACL.config.aci.2=o=mycompany,c=us#entry#grant:r,s,c,p#[all]#subtree:ou=dir2,o=company,c=us
server.globalChain.ACL.config.aci.3=o=mycompany,c=us#subtree#grant:r,s,c,p#[all]#subtree:ou=dir2,o=company,c=us
server.globalChain.ACL.config.aci.4=CN=ROOTDSE#entry#grant:v#[entry]#public:
server.globalChain.ACL.config.aci.5=CN=ROOTDSE#entry#grant:r,s,c,p#[all]#public:
```

**Comment by mlbiam** [comment]
> As to uid=admin,ou=system, all over in the log I see: "creatorsname: uid=admin,ou=system".
Then, near the end of initialization, in the log, I see "WARN DefaultDirectoryService - You didn't change the admin password of directory service instance 'null'. Please update the admin password as soon as possible to prevent a possible security breach." As I see that ApacheDS is embedded I had found http://directory.apache.org/apacheds/basic-ug/1.4.2-changing-admin-password.html but that default password never worked to bind and the object is not located.

Ah, I see.  Yes, we're using ApacheDS for our LDAP layer.  Those messages can be ignored as no persistent storage is ever created.  We tried to remove/change as little code as possible when doing the integration to make it easier to upgrade down the road.

 
> Turn off anonymous bind & Allow any valid user to bind, view, read, search.

Give this ACLs set a try.  Its based off of a common template I use:

```
server.globalChain.ACL.className=net.sourceforge.myvd.inserts.accessControl.AccessMgmt
server.globalChain.ACL.config.numACIs=6
server.globalChain.ACL.config.aci.0=o=mycompany,c=us#subtree#deny:a,d,n,v#[entry]#public:
server.globalChain.ACL.config.aci.1=o=mycompany,c=us#subtree#deny:w,o,s,c,p#[all]#public:
server.globalChain.ACL.config.aci.2=CN=ROOTDSE#entry#grant:r,w,s,c,p#[all]#public:
server.globalChain.ACL.config.aci.3=CN=ROOTDSE#entry#grant:v#[entry]#public:
server.globalChain.ACL.config.aci.4=o=mycompany,c=us#subtree#grant:v#[entry]#subtree:o=mycompany,c=us
server.globalChain.ACL.config.aci.5=o=mycompany,c=us#subtree#grant:w,o,s,c,p#[all]#subtree:o=mycompany,c=us
```

The first two ACLs stop all operations for anonymous users.  The third & forth opens up the ROOT DSE.  The last two open up your search root to authenticated users.

> Ok, I think I found a bug. Bob can bind, view, query with:

Your subject scope is `ou=dir2,o=company,c=us` and I think you meant `ou=dir2,o=mycompany,c=us` (you dropped the "my" in "mycompany"?  I'm actually surprised it failed at all since there's no `deny` statement so I'll need to double check.  In the ACL insert order matters and its not a "deny by default" setup so without an explicit deny statement it shouldn't really fail on anything.

**Comment by partdeadpool-partpunisher** [comment]
Thanks for the feedback!
Ugghhhh. I hate typos. That fixed it up. Did you mean "c" instead of "a" in the entry permissions? 

Ok. So everything works as expected loading, listening, authenticating, and ACL'ing.
So I added a keystore with a signed cert (internal CA). Changed the listener to 636
```
# server.listener.port=10389
server.secure.listener.port=636
server.secure.keystore=keystore
server.secure.keypass=<store password>
```
Restart, test. That all works great!

My DC has a cert, signed by the same CA. More changes and another restart.
```
server.ad1.ldap1.config.config.type=LDAPS
server.ad1.ldap1.config.port=636
```
Not able to connect to the virtualdirectory now. I can connect to the DC fine on 636 with an LDAP browser or ldp though. In addition to generic "Connect Error" messages, I find the following in the debug log:
```
DEBUG SslHandler - Unexpected exception from SSLEngine.closeInbound().
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
```
Thoughts?

**Comment by mlbiam** [comment]
> And I found out that the init file needs to match my change to the keystore name!! :-)

Yeah, we hard coded it in the init scripts to make it easier to deploy. 

So you're good?  We can close this out?

**Comment by partdeadpool-partpunisher** [comment]
Yes. Thanks so much for your time and information.
