### ISSUE TITLE
query result limited at 1000 entries

### ISSUE THREAD

**Issue by spopoff** [TremoloSecurity/MyVirtualDirectory#59]
Hello,

I have a limitation on query result at 1000 entries. Where can I overide this limitation ?
In my configuration I use this parameter but it didn't make the job:

server.InternalUser.LDAPInternalUser.config.maxResults=20000
server.InternalService.LDAPInternalSrv.config.maxResults=20000
server.ExternalUser.LDAPExternalUser.config.maxResults=20000
server.InternalGroup.LDAPInternalGroup.config.maxResults=20000
server.ExternalGroup.LDAPExternalGroup.config.maxResults=20000
server.InternalApplication.LDAPInternalApp.config.maxResults=20000

It seems that limitation is the same as with Apache Directory studio.

Best regards,

Stéphane POPOFF

**Comment by mlbiam** [comment]
@spopoff what is your backend?  I don't think there's a built in limit

**Comment by spopoff** [comment]
Hi,

I found a limit in the Novell LDAPSearchConstraints class that is never set, so default is 1000.

package com.novell.ldap;

import com.novell.ldap.client.Debug;
import java.util.Hashtable;

public class LDAPSearchConstraints
  extends LDAPConstraints
{
  private int dereference = 0;
  private int serverTimeLimit = 0;
  private int maxResults = 1000;
  private int batchSize = 1;
  private static Object nameLock = new Object();
  private static int lSConsNum = 0;
  private String name;
  public static final int DEREF_NEVER = 0;
  public static final int DEREF_SEARCHING = 1;
  public static final int DEREF_FINDING = 2;
  public static final int DEREF_ALWAYS = 3;

**Comment by spopoff** [comment]
Ok,
I've seen you have a maxResults property, but acts only on jdbc connection. Maybe you can extend this property to Ldap search ?

**Comment by mlbiam** [comment]
this is now fixed in the 1.0.6 branch.  wasn't passing the constraints.
