### ISSUE TITLE
case insensitive search

### ISSUE THREAD

**Issue by KarlKnapp** [TremoloSecurity/MyVirtualDirectory#60]
I'm usinga a JDBC Insert and when I search for the Name "Miller" the Filter (sn=Mill*) returns the desired result, but (sn=mill*) returns nothing. Is there any configuration to allow case-insensitive filters or am I missing something?

**Comment by mlbiam** [comment]
its a function of the database.  we just pass the query to the db.  So it would go from `(sn=mill*)` to `WHERE sn LIKE `mill%` . What db are you using?

**Comment by KarlKnapp** [comment]
MariaDB

**Comment by KarlKnapp** [comment]
I've checked that the right result is coming from the db, and is added to the result list. Is there any filter mechanism oder something that changes the result list afterwards? Please find attached log files.

[working.txt](https://github.com/TremoloSecurity/MyVirtualDirectory/files/3202561/working.txt)
[notWorking.txt](https://github.com/TremoloSecurity/MyVirtualDirectory/files/3202562/notWorking.txt)

**Comment by mlbiam** [comment]
huh, yes we are doing a check that the filter is correct.  it might be more restrictive then it probably should be.  Can you configure dumptransactions right infront of your jdbc insert?  that way i can see where the filter is getting checked.

**Comment by KarlKnapp** [comment]
So, remove this block

#Configure global chains
server.globalChain=LogAllTransactions
server.globalChain.LogAllTransactions.className=net.sourceforge.myvd.inserts.DumpTransaction
server.globalChain.LogAllTransactions.config.logLevel=info
server.globalChain.LogAllTransactions.config.label=Global


and configuring it like this?

#Database insert
server.DBContacts.chain=kerberos,C,DT,DB
server.DBContacts.nameSpace=dc=meta
server.DBContacts.weight=0
server.DBContacts.kerberos.className=net.sourceforge.myvd.inserts.kerberos.KerberosInterceptor

server.DBContacts.C.className=net.sourceforge.myvd.inserts.jdbc.CompositeAttrib
server.DBContacts.C.config.attribute=fullName
server.DBContacts.C.config.components=givenname:ls,sn:*
server.DBContacts.C.config.objectClass=contactPerson

server.DBContacts.DT.className=net.sourceforge.myvd.inserts.DumpTransaction

server.DBContacts.DB.className=net.sourceforge.myvd.inserts.jdbc.JdbcInsert
server.DBContacts.DB.config.driver=org.mariadb.jdbc.Driver
server.DBContacts.DB.config.url=jdbc.....

**Comment by mlbiam** [comment]
yep

**Comment by KarlKnapp** [comment]
[myvd.log](https://github.com/TremoloSecurity/MyVirtualDirectory/files/3203102/myvd.log)

**Comment by mlbiam** [comment]
I'm going to run this through our QA process and assuming everything checks out publish a beta of 1.0.6 for you to try with.

**Comment by mlbiam** [comment]
Here's a download link for the beta - https://www.tremolosecurity.com/dwn/tremolosecurity-downloads/myvd/1.0.6/myvd-server-1.0.6.tar.gz

**Comment by KarlKnapp** [comment]
Works like a charm! Thanks for the quick fix!
