### ISSUE TITLE
SQL mapping not working for alias column names

### ISSUE THREAD

**Issue by KarlKnapp** [TremoloSecurity/MyVirtualDirectory#66]
I'm trying to map values from renamed columns, sadly 'mobile' and 'phone' are not in the result. Is this a bug or am I missing something?

`server.DBContacts.DB.config.mapping=uid=customerId,phoneNo=phone,mobileNo=mobile`

```
SELECT db.customerId,
       a.value AS phone,
       b.value AS mobile
FROM   mydb.customers AS db
LEFT JOIN mydb.numbers AS a ON (a.customerId = db.customerId AND a.type = 'phone')
LEFT JOIN mydb.numbers AS b ON (b.customerId = db.customerId AND b.type = 'mobile')
```

> [2019-07-11 14:17:44,299][NioProcessor-2] DEBUG LdapResponseHandler - Message Sent : MessageType : SEARCH_RESULT_ENTRY
> Message ID : 34
>     Search Result Entry
> Entry
>     dn: uid=31376,dc=meta
>     objectClass: 0x63 0x6F 0x6E 0x74 0x61 0x63 0x74 0x50 0x65 0x72 0x73 0x6F 0x6E 
>     uid: 0x33 0x31 0x33 0x37 0x36 

Please let me know if you need further information.

**Comment by mlbiam** [comment]
So it should fail in my unit tests but derby seems to be more forgiving than MySQL.  Can you try the 1.0.7 branch?

**Comment by KarlKnapp** [comment]
Works perfect! Thanks for the quick response!
