### ISSUE TITLE
password for DefaultDirectoryService ... do I need to worry?

### ISSUE THREAD

**Issue by wjcarpenter** [TremoloSecurity/MyVirtualDirectory#80]
Every time I start MyVD, I see this error in the log file.

> [2019-12-28 21:31:47,189][main] WARN  DefaultDirectoryService - You didn't change the admin password of directory service instance 'null'.  Please update the admin password as soon as possible to prevent a possible security breach.

It's easy to track down where this comes from and the way to fix it in a vanilla setup (https://directory.apache.org/apacheds/basic-ug/1.4.2-changing-admin-password.html). However, with the MyVD layer above it, the recipe for changing it doesn't work. (I don't have the LDAP namespace for the admin user indicated.)

I tried to figure out if this is something that matters in a MyVD setup, but I'm just not sure. Could you comment on this? I don't want to leave a backdoor open, but I also don't want to worry about something that doesn't actually matter.

**Comment by mlbiam** [comment]
This can be ignored.  this password is not referenced anywhere in MyVD or OpenUnison
